import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import ResponsiveNav from "@/components/common/NavBar/ResponsiveNav";

const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: 'Home | Ecommerce',
    template: "%s | Ecommerce"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <ResponsiveNav />
        <NextTopLoader />
        {children}</body>
    </html>
  );
}
